### PR TITLE
fix: provider could not be found error

### PR DESCRIPTION
**Pull request by tnc1997**

### CODE REVIEW

**Comment by tnc1997** [comment]
It looks like perhaps the different formats of import statement might have been causing issues?

I was able to get the font size changing as intended with these changes and the following configuration:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by devpawann** [comment]
One line of wrong Import statement ruined my day.
I can't thank you in a word. It worked now

**Comment by tnc1997** [comment]
You're welcome, happy to help :smile: 

It is an easy issue to create inadvertently, especially with IDE auto-imports :wink:

**Comment by devpawann** [comment]
I will never trust Auto Import again.
Great lesson learned today.

This app is for someone else, I am creating so I can't make it open source.
So I should make it private for now.
Again thank you :)

**Pull request merged**
